// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC1Jd9owL1oQhPBWLio98jH8DhL0TXNEs',
    appId: '1:545466731341:android:ab1b882c580f3160670504',
    messagingSenderId: '545466731341',
    projectId: 'playclone-28e26',
    storageBucket: 'playclone-28e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdiNGjFCymWgaMpaNRfwIY9vm3ba_o2M',
    appId: '1:545466731341:ios:a31ff968ec72117f670504',
    messagingSenderId: '545466731341',
    projectId: 'playclone-28e26',
    storageBucket: 'playclone-28e26.firebasestorage.app',
    iosBundleId: 'com.example.googleplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXRTNbx1KHZrw025L5OFCfro7A_jppY5E',
    appId: '1:545466731341:web:64d5d830ae0108a2670504',
    messagingSenderId: '545466731341',
    projectId: 'playclone-28e26',
    authDomain: 'playclone-28e26.firebaseapp.com',
    storageBucket: 'playclone-28e26.firebasestorage.app',
    measurementId: 'G-YWV8N9N45R',
  );
}
